// Source de vérité des 16 dictées 5e (progression de la collègue, août 2026).
// Généré depuis ~/Dev/dictee-v2/lib/dictees-5e-data.ts avec distracteurs
// retravaillés : orthographe LEXICALE uniquement (garde-fou Nadia — jamais
// d'accord ni de conjugaison). Consommé par generate-seed-5e.mjs.



function w(word, definition, spellingErrors, position) {
  return { word, definition, spellingErrors, position };
}

export const DICTEES_5E_DATA = [
  {
    id: 'dictee-5e-1',
    title: 'Dictée n°1',
    shareCode: '5EME01',
    level: '5e',
    orthoPoint: 'a / à ; et / est',
    lexicalTheme: "l'observation",
    starWord: 'scruter',
    words: [
      w('scruter', "Observer avec une très grande attention pour découvrir un détail", ['scrutter', 'skruter', 'scruther'], 0),
      w('examiner', "Regarder quelque chose avec soin pour bien le connaître", ['éxaminer', 'examinner', 'exsaminer'], 1),
      w('apercevoir', "Voir rapidement ou de loin, sans bien distinguer", ['appercevoir', 'apersevoir', 'apercevoire'], 2),
      w('observer', "Regarder attentivement pour étudier", ['obcerver', 'opserver', 'obsserver'], 3),
      w('un détail', "Petit élément d'un ensemble", ['un détaille', 'un detail', 'un détaile'], 4),
      w('un indice', "Signe qui aide à découvrir la vérité", ['un indisse', 'un endice', 'un indyce'], 5),
      w('le regard', "Action de diriger les yeux vers quelque chose", ['le regart', 'le reguard', 'le regare'], 6),
      w('curieux', "Qui a envie de découvrir et de comprendre", ['curieu', 'qurieux', 'curyeux'], 7),
      w('visible', "Que l'on peut voir", ['vissible', 'vizible', 'visibl'], 8),
      w('attentivement', "En faisant très attention", ['atentivement', 'attentivemant', 'attentivemment'], 9),
    ],
    dictationText:
      "À l'entrée du village, Lina s'arrête devant une vieille maison. Elle observe attentivement les fenêtres et examine la porte. Un détail attire le regard : une pierre est déplacée et laisse apparaître une petite marque. Lina vient aussi d'apercevoir un indice dans la poussière. Elle reste à distance. À cet endroit, tout est calme. La jeune fille est curieuse. Elle a le sentiment que la maison cache un secret. Elle avance lentement et se demande à qui appartient la maison.",
    fillBlanksText:
      "À l'entrée du village, Lina s'arrête devant une vieille maison. Elle {{observe}} {{attentivement}} les fenêtres et {{examine}} la porte. Un {{détail}} attire le {{regard}} : une pierre est déplacée et laisse apparaître une petite marque. Lina vient aussi d'{{apercevoir}} un {{indice}} dans la poussière. Elle reste à distance. À cet endroit, tout est calme. La jeune fille est {{curieuse}}. Elle a le sentiment que la maison cache un secret. Elle avance lentement et se demande à qui appartient la maison.",
  },
  {
    id: 'dictee-5e-2',
    title: 'Dictée n°2',
    shareCode: '5EME02',
    level: '5e',
    orthoPoint: 'on / ont ; son / sont',
    lexicalTheme: "l'exploration",
    starWord: 'arpenter',
    words: [
      w('arpenter', "Parcourir à grands pas ou en tous sens", ['arpanter', 'arpentter', 'harpenter'], 0),
      w('contourner', "Faire le tour d'un obstacle pour l'éviter", ['containner', 'contournner', 'comtourner'], 1),
      w("s'aventurer", "Aller quelque part malgré le risque", ["s'avanturer", "s'aventurrer", "s'aventhurer"], 2),
      w('un sentier', "Chemin étroit dans la nature", ['un santier', 'un centier', 'un sentié'], 3),
      w('un périple', "Long voyage avec de nombreuses étapes", ['un péripple', 'un perriple', 'un péripl'], 4),
      w('un détour', "Chemin plus long que le trajet direct", ['un daitour', 'un détourt', 'un déttour'], 5),
      w('un paysage', "Étendue de pays que l'on voit d'un endroit", ['un payssage', 'un paisage', 'un payzage'], 6),
      w('un itinéraire', "Chemin à suivre pour aller d'un lieu à un autre", ['un itinérère', 'un ittinéraire', 'un itinairaire'], 7),
      w('isolé', "Éloigné de tout, séparé des autres", ['izolé', 'issolé', 'isollé'], 8),
      w('inexploré', "Que personne n'a encore exploré", ['innexploré', 'inéxploré', 'inexplorré'], 9),
    ],
    dictationText:
      "Au matin, les voyageurs s'aventurent sur un sentier isolé. Ils ont un itinéraire précis à suivre et la région est inexplorée. Leur périple commence par un long détour autour d'une rivière. Ils arpentent ensuite des montagnes et contournent des roches. Le paysage devient plus sauvage. À midi, ils aperçoivent une cabane. Elle est à plusieurs heures de marche et ils sont heureux de trouver un refuge. André sort de son sac leur déjeuner. Ils sont épuisés mais n'ont qu'une envie : poursuivre l'exploration !",
    fillBlanksText:
      "Au matin, les voyageurs {{s'aventurent}} sur un {{sentier}} {{isolé}}. Ils ont un {{itinéraire}} précis à suivre et la région est {{inexplorée}}. Leur {{périple}} commence par un long {{détour}} autour d'une rivière. Ils {{arpentent}} ensuite des montagnes et {{contournent}} des roches. Le {{paysage}} devient plus sauvage. À midi, ils aperçoivent une cabane. Elle est à plusieurs heures de marche et ils sont heureux de trouver un refuge. André sort de son sac leur déjeuner. Ils sont épuisés mais n'ont qu'une envie : poursuivre l'exploration !",
  },
  {
    id: 'dictee-5e-3',
    title: 'Dictée n°3',
    shareCode: '5EME03',
    level: '5e',
    orthoPoint: 'ce / se ; ces / ses',
    lexicalTheme: 'la prudence et la méfiance',
    starWord: 'présager',
    words: [
      w('présager', "Annoncer ce qui va se produire, laisser prévoir", ['prézager', 'préssager', 'praisager'], 0),
      w('se méfier', "Ne pas faire confiance, rester sur ses gardes", ['se méffier', 'se méphier', 'se maifier'], 1),
      w('se dissimuler', "Se cacher pour ne pas être vu", ['se dicimuler', 'se disimuler', 'se dissimuller'], 2),
      w('guetter', "Surveiller attentivement en attendant quelque chose", ['guéter', 'ghetter', 'gueter'], 3),
      w('une menace', "Danger possible", ['une menasse', 'une mennace', 'une menaçe'], 4),
      w('la vigilance', "Surveillance attentive et continue", ['la vigillance', 'la vijilance', 'la vigilence'], 5),
      w("l'inquiétude", "Peur légère, souci", ["l'inquiètude", "l'inquiétute", "l'einquiétude"], 6),
      w('une alerte', "Signal qui prévient d'un danger", ['une allerte', 'une alairte', 'une alertte'], 7),
      w('inhabituel', "Qui n'arrive pas d'habitude, anormal", ['inabituel', 'innhabituel', 'inhabittuel'], 8),
      w('prudemment', "Avec prudence, en faisant attention", ['prudament', 'prudemant', 'prudemement'], 9),
    ],
    dictationText:
      "Le chemin devient étroit et les voyageurs se méfient de ce silence qui les entoure. Ils se dissimulent derrière les arbres et, à chaque bruit, ils se retournent avec inquiétude. Ils guettent le moindre signe d'une menace. Leur vigilance est constante car une alerte peut surgir à tout moment. Soudain, l'un d'entre eux entend un bruit inhabituel et présage un danger. Il redouble d'attention, avance prudemment et observe les buissons. Ses compagnons le suivent en silence. Bientôt, tous se demandent si un danger est vraiment à craindre.",
    fillBlanksText:
      "Le chemin devient étroit et les voyageurs {{se méfient}} de ce silence qui les entoure. Ils {{se dissimulent}} derrière les arbres et, à chaque bruit, ils se retournent avec {{inquiétude}}. Ils {{guettent}} le moindre signe d'une {{menace}}. Leur {{vigilance}} est constante car une {{alerte}} peut surgir à tout moment. Soudain, l'un d'entre eux entend un bruit {{inhabituel}} et {{présage}} un danger. Il redouble d'attention, avance {{prudemment}} et observe les buissons. Ses compagnons le suivent en silence. Bientôt, tous se demandent si un danger est vraiment à craindre.",
  },
  {
    id: 'dictee-5e-4',
    title: 'Dictée n°4',
    shareCode: '5EME04',
    level: '5e',
    orthoPoint: 'é / er / ez',
    lexicalTheme: 'la lumière',
    starWord: 'irradier',
    words: [
      w('irradier', "Se répandre en rayonnant, comme une lumière", ['iradier', 'irradyer', 'irrradier'], 0),
      w('scintiller', "Briller en jetant de petits éclats de lumière", ['sintiller', 'scintiler', 'çintiller'], 1),
      w('refléter', "Renvoyer une image ou une lumière", ['reffléter', 'refleter', 'reflaiter'], 2),
      w('illuminer', "Éclairer d'une vive lumière", ['iluminer', 'iluminner', 'ilumminer'], 3),
      w('faiblir', "Perdre de sa force ou de son intensité", ['féblir', 'faiblire', 'faibllir'], 4),
      w('la pénombre', "Lumière faible, entre l'ombre et la clarté", ['la pénonbre', 'la painombre', 'la pénombe'], 5),
      w('une lueur', "Lumière faible ou passagère", ['une luer', 'une lueure', 'une luheur'], 6),
      w('un rayon', "Trait de lumière", ['un raillon', 'un rayont', 'un réyon'], 7),
      w('un éclat', "Lumière vive et brillante", ['un écla', 'un éclas', 'un aiclat'], 8),
      w('éblouissant', "Si brillant qu'il gêne les yeux", ['éblouisant', 'ébluissant', 'éblouïssant'], 9),
    ],
    dictationText:
      "Le soleil commence à descendre derrière les hautes montagnes. Ses derniers rayons ont déjà illuminé le paysage et une lueur dorée se reflète sur les eaux profondes du lac. Au loin, vous regardez les sommets qui semblent scintiller. Peu à peu, la lumière faiblit et la pénombre gagne les chemins. Pourtant, les pierres conservent un éclat presque éblouissant. Une bande rose irradie au-dessus des nuages. Vous, voyageurs fatigués, vous levez les yeux pour admirer le ciel et vous restez silencieux devant ce sublime spectacle de la nature.",
    fillBlanksText:
      "Le soleil commence à descendre derrière les hautes montagnes. Ses derniers {{rayons}} ont déjà {{illuminé}} le paysage et une {{lueur}} dorée se {{reflète}} sur les eaux profondes du lac. Au loin, vous regardez les sommets qui semblent {{scintiller}}. Peu à peu, la lumière {{faiblit}} et la {{pénombre}} gagne les chemins. Pourtant, les pierres conservent un {{éclat}} presque {{éblouissant}}. Une bande rose {{irradie}} au-dessus des nuages. Vous, voyageurs fatigués, vous levez les yeux pour admirer le ciel et vous restez silencieux devant ce sublime spectacle de la nature.",
  },
  {
    id: 'dictee-5e-5',
    title: 'Dictée n°5',
    shareCode: '5EME05',
    level: '5e',
    orthoPoint: "L'accord sujet-verbe au présent",
    lexicalTheme: "l'émerveillement",
    starWord: 'enchantement',
    words: [
      w('un enchantement', "Émerveillement magique, charme extraordinaire", ['un anchantement', 'un enchantemant', 'un enchentement'], 0),
      w('admirer', "Regarder avec plaisir ce que l'on trouve beau", ['atmirer', 'admirrer', 'admiirer'], 1),
      w('contempler', "Regarder longuement avec admiration", ['contanpler', 'contempller', 'comtempler'], 2),
      w("s'émerveiller", "Éprouver une grande admiration mêlée de surprise", ["s'émervailler", "s'émmerveiller", "s'émerveyer"], 3),
      w("s'extasier", "Montrer une admiration très vive", ["s'extazier", "s'exthasier", "s'exstasier"], 4),
      w('une merveille', "Chose qui provoque une grande admiration", ['une merveil', 'une mervaille', 'une mérveille'], 5),
      w('un éblouissement', "Émerveillement si fort qu'il éblouit", ['un éblouisement', 'un ébluissement', 'un éblouissemant'], 6),
      w('fascinant', "Qui attire et retient irrésistiblement l'attention", ['facinant', 'fassinant', 'fascinnant'], 7),
      w('envoûtant', "Qui charme comme par magie", ['envoutant', 'anvoûtant', 'envoûttant'], 8),
      w('profondément', "De manière très forte, intense", ['profondement', 'profondémant', 'proffondément'], 9),
    ],
    dictationText:
      "Sur la grande place, un spectacle attire les habitants. Les enfants admirent les artistes, s'émerveillent devant les couleurs et s'extasient devant les costumes. Les musiciens jouent une mélodie envoûtante que le public écoute en silence. Au fond, derrière les musiciens et les spectateurs, se dressent de grands décors colorés. La foule se bouscule car chacun veut admirer ce spectacle fascinant de près et les plus jeunes s'émerveillent devant chaque nouvelle scène. Sur les visages naissent des sourires. Cette merveille plaît à tous et enchante même les adultes. Profondément touchés, ils restent longtemps à contempler les artistes.",
    fillBlanksText:
      "Sur la grande place, un spectacle attire les habitants. Les enfants {{admirent}} les artistes, {{s'émerveillent}} devant les couleurs et {{s'extasient}} devant les costumes. Les musiciens jouent une mélodie {{envoûtante}} que le public écoute en silence. Au fond, derrière les musiciens et les spectateurs, se dressent de grands décors colorés. La foule se bouscule car chacun veut admirer ce spectacle {{fascinant}} de près et les plus jeunes s'émerveillent devant chaque nouvelle scène. Sur les visages naissent des sourires. Cette {{merveille}} plaît à tous et enchante même les adultes. {{Profondément}} touchés, ils restent longtemps à {{contempler}} les artistes.",
  },
  {
    id: 'dictee-5e-6',
    title: 'Dictée n°6',
    shareCode: '5EME06',
    level: '5e',
    orthoPoint: "L'accord dans le groupe nominal (déterminant-nom-adjectif)",
    lexicalTheme: "l'effort et la volonté",
    starWord: 'persévérance',
    words: [
      w('la persévérance', "Qualité de celui qui continue ses efforts sans se décourager", ['la perséverance', 'la persévérence', 'la perceverance'], 0),
      w('entreprendre', "Commencer à faire quelque chose d'important", ['entreprandre', 'antreprendre', 'entrepremdre'], 1),
      w("s'efforcer", "Faire tous ses efforts pour réussir", ["s'éforcer", "s'efforsser", "s'esforcer"], 2),
      w('le courage', "Force qui permet d'affronter les difficultés", ['le courrage', 'le couraje', 'le kourage'], 3),
      w('un effort', "Énergie que l'on dépense pour réussir", ['un éfort', 'un effor', 'un èffort'], 4),
      w('déterminé', "Qui est décidé, qui sait ce qu'il veut", ['determiné', 'déterminné', 'détérminé'], 5),
      w('opiniâtre', "Qui ne renonce jamais, très obstiné", ['opiniatre', 'oppiniâtre', 'opignâtre'], 6),
      w('tenace', "Qui tient bon, qui n'abandonne pas", ['tenasse', 'tennace', 'thenace'], 7),
      w('résolument', "Avec décision, sans hésiter", ['résolumment', 'raisolument', 'rézolument'], 8),
      w('inlassablement', "Sans jamais se fatiguer ni s'arrêter", ['inlasablement', 'inlassablemant', 'einlassablement'], 9),
    ],
    dictationText:
      "Depuis plusieurs semaines, Manon prépare un spectacle de marionnettes. Avec une grande détermination, elle entreprend de fabriquer de nouvelles marionnettes et s'efforce de leur donner des expressions vivantes. Malgré ses longues soirées de travail, sa persévérance et son courage ne faiblissent pas. Cette jeune artiste déterminée, opiniâtre et tenace sait que chaque effort a une valeur. Elle travaille résolument et inlassablement pour terminer cet incroyable décor. Un soir, tout est prêt. « Préparez vos costumes ! » peut-elle enfin dire à ses camarades. Les spectateurs vont bientôt pouvoir profiter du spectacle et d'une soirée probablement magique.",
    fillBlanksText:
      "Depuis plusieurs semaines, Manon prépare un spectacle de marionnettes. Avec une grande détermination, elle {{entreprend}} de fabriquer de nouvelles marionnettes et {{s'efforce}} de leur donner des expressions vivantes. Malgré ses longues soirées de travail, sa {{persévérance}} et son {{courage}} ne faiblissent pas. Cette jeune artiste {{déterminée}}, {{opiniâtre}} et {{tenace}} sait que chaque {{effort}} a une valeur. Elle travaille {{résolument}} et {{inlassablement}} pour terminer cet incroyable décor. Un soir, tout est prêt. « Préparez vos costumes ! » peut-elle enfin dire à ses camarades. Les spectateurs vont bientôt pouvoir profiter du spectacle et d'une soirée probablement magique.",
  },
  {
    id: 'dictee-5e-7',
    title: 'Dictée n°7',
    shareCode: '5EME07',
    level: '5e',
    orthoPoint: "Les terminaisons de l'imparfait (-ais, -ait, -ions…)",
    lexicalTheme: 'le relief et la montagne',
    starWord: 'serpenter',
    words: [
      w('serpenter', "Suivre un chemin qui fait de nombreux virages", ['serpanter', 'serpentter', 'sérpenter'], 0),
      w("s'élever", "Monter, se dresser vers le haut", ["s'éllever", "s'élevver", "s'éléver"], 1),
      w('surplomber', "Dominer en avançant au-dessus du vide", ['surplonber', 'surplommber', 'surplommer'], 2),
      w('culminer', "Atteindre son point le plus haut", ['culmminer', 'kulminer', 'qulminer'], 3),
      w('un sommet', "Point le plus haut d'une montagne", ['un somet', 'un sommé', 'un sommait'], 4),
      w('un versant', "Pente d'une montagne", ['un vairsant', 'un verssant', 'un versan'], 5),
      w('une falaise', "Paroi rocheuse très raide, souvent au bord de la mer", ['une fallaise', 'une falèse', 'une phalaise'], 6),
      w('escarpé', "En pente raide, difficile à gravir", ['aiscarpé', 'éscarpé', 'escarppé'], 7),
      w('abrupt', "Très raide, presque vertical", ['abruppt', 'abrup', 'habrupt'], 8),
      w('majestueusement', "Avec une beauté imposante et noble", ['magestueusement', 'majestueusemant', 'majestueuzement'], 9),
    ],
    dictationText:
      "La montagne s'élevait devant les voyageurs et dominait toute la vallée. Le sentier serpentait sur un versant escarpé, puis longeait une falaise abrupte. Plus haut, les sommets semblaient culminer sous les épais nuages gris. Un grand rocher surplombait le chemin et obligeait les marcheurs à ralentir. Malgré la pente, ils avançaient avec prudence. Ils continuaient inlassablement leur marche pour atteindre le refuge avant la nuit. Le soleil éclairait majestueusement les reliefs. À mesure qu'ils montaient, la vallée paraissait plus petite. Ils s'arrêtaient parfois pour admirer ce paysage envoûtant et reprenaient ensuite rapidement leur marche.",
    fillBlanksText:
      "La montagne {{s'élevait}} devant les voyageurs et dominait toute la vallée. Le sentier {{serpentait}} sur un {{versant}} {{escarpé}}, puis longeait une {{falaise}} {{abrupte}}. Plus haut, les {{sommets}} semblaient {{culminer}} sous les épais nuages gris. Un grand rocher {{surplombait}} le chemin et obligeait les marcheurs à ralentir. Malgré la pente, ils avançaient avec prudence. Ils continuaient inlassablement leur marche pour atteindre le refuge avant la nuit. Le soleil éclairait {{majestueusement}} les reliefs. À mesure qu'ils montaient, la vallée paraissait plus petite. Ils s'arrêtaient parfois pour admirer ce paysage envoûtant et reprenaient ensuite rapidement leur marche.",
  },
  {
    id: 'dictee-5e-8',
    title: 'Dictée n°8',
    shareCode: '5EME08',
    level: '5e',
    orthoPoint: 'Les terminaisons du passé simple (3e personne surtout)',
    lexicalTheme: "l'inconnu et le mystère",
    starWord: 'énigmatique',
    words: [
      w('énigmatique', "Difficile à comprendre, mystérieux", ['énigmatic', 'énigmattique', 'énygmatique'], 0),
      w('disparaître', "Cesser d'être visible", ['disparaitre', 'dispareître', 'dissparaître'], 1),
      w('surgir', "Apparaître brusquement", ['surjir', 'surgire', 'sûrgir'], 2),
      w('déceler', "Découvrir ce qui était caché", ['déseler', 'décceler', 'désseler'], 3),
      w('dévoiler', "Révéler ce qui était secret", ['daivoiler', 'dévoiller', 'dévoualer'], 4),
      w('une silhouette', "Forme générale d'une personne vue de loin ou dans l'ombre", ['une silouette', 'une silhouète', 'une sillouette'], 5),
      w('une apparition', "Fait de se montrer soudainement", ['une aparition', 'une apparission', 'une apparittion'], 6),
      w('étrange', "Qui surprend, inhabituel et mystérieux", ['étranje', 'aitrange', 'étrangge'], 7),
      w('insaisissable', "Que l'on ne peut ni attraper ni comprendre", ['insaisisable', 'insésissable', 'inssaisissable'], 8),
      w('mystérieusement', "D'une manière étrange et inexpliquée", ['mistérieusement', 'mystérieusemant', 'mystérieuzement'], 9),
    ],
    dictationText:
      "Au fond d'une vallée, les voyageurs découvrirent une grande maison de pierre qu'aucune carte ne signalait. L'un d'eux avança et aperçut une silhouette étrange derrière la porte. Elle surgit tout à coup dans la pénombre, puis disparut. Les compagnons cherchèrent à déceler un signe, mais rien ne leur permit de comprendre cette apparition. Peu à peu, un symbole se dévoila sur le mur. Sa forme était presque insaisissable. Ils entrèrent prudemment et avancèrent dans le couloir. Une voix résonna alors derrière eux et ils se retournèrent avec inquiétude. Il n'y avait personne mais la lourde porte se referma mystérieusement.",
    fillBlanksText:
      "Au fond d'une vallée, les voyageurs découvrirent une grande maison de pierre qu'aucune carte ne signalait. L'un d'eux avança et aperçut une {{silhouette}} {{étrange}} derrière la porte. Elle {{surgit}} tout à coup dans la pénombre, puis {{disparut}}. Les compagnons cherchèrent à {{déceler}} un signe, mais rien ne leur permit de comprendre cette {{apparition}}. Peu à peu, un symbole se {{dévoila}} sur le mur. Sa forme était presque {{insaisissable}}. Ils entrèrent prudemment et avancèrent dans le couloir. Une voix résonna alors derrière eux et ils se retournèrent avec inquiétude. Il n'y avait personne mais la lourde porte se referma {{mystérieusement}}.",
  },
  {
    id: 'dictee-5e-9',
    title: 'Dictée n°9',
    shareCode: '5EME09',
    level: '5e',
    orthoPoint: 'Le plus-que-parfait',
    lexicalTheme: 'la ruse',
    starWord: 'perfidie',
    words: [
      w('la perfidie', "Méchanceté de celui qui trahit en cachette", ['la perfidi', 'la pairfidie', 'la perffidie'], 0),
      w('leurrer', "Tromper par de fausses apparences", ['leurer', 'lheurrer', 'leaurer'], 1),
      w('feindre', "Faire semblant", ['faindre', 'feindres', 'feintre'], 2),
      w('manigancer', "Préparer en secret un mauvais coup", ['maniganser', 'manigencer', 'manniganser'], 3),
      w('dissimuler', "Cacher volontairement", ['disimuler', 'diçimuler', 'dissimmuler'], 4),
      w('un stratagème', "Ruse habile pour tromper", ['un stratagem', 'un stratagéme', 'un strattagème'], 5),
      w('la malice', "Esprit moqueur qui aime jouer des tours", ['la malisse', 'la mallice', 'la malyce'], 6),
      w('fourbe', "Qui trompe avec hypocrisie", ['fourb', 'fourbbe', 'phourbe'], 7),
      w('sournois', "Qui cache ses véritables intentions", ['sournoi', 'sournnois', 'sournoit'], 8),
      w('astucieusement', "Avec habileté et intelligence", ['astucieusemant', 'astussieusement', 'astucieuzement'], 9),
    ],
    dictationText:
      "Les voyageurs firent face, dans une autre vallée, à un très ancien château. Ils ne s'attendaient pas à découvrir un lieu aussi étrange. Depuis longtemps, une légende évoquait un passage secret sous les ruines. Le guide avait étudié plusieurs cartes et avait astucieusement préparé son stratagème car, pour visiter ce passage, il fallait leurrer les gardes qui bloquaient l'accès. Le guide feignit donc de chercher l'entrée principale, alors qu'il avait repéré une porte dissimulée. Les autres le suivirent. Il avait manigancé cette ruse avec malice pour éviter les gardes qui surveillaient le chemin. Son plan, imaginé longtemps à l'avance, fonctionna parfaitement.",
    fillBlanksText:
      "Les voyageurs firent face, dans une autre vallée, à un très ancien château. Ils ne s'attendaient pas à découvrir un lieu aussi étrange. Depuis longtemps, une légende évoquait un passage secret sous les ruines. Le guide avait étudié plusieurs cartes et avait {{astucieusement}} préparé son {{stratagème}} car, pour visiter ce passage, il fallait {{leurrer}} les gardes qui bloquaient l'accès. Le guide {{feignit}} donc de chercher l'entrée principale, alors qu'il avait repéré une porte {{dissimulée}}. Les autres le suivirent. Il avait {{manigancé}} cette ruse avec {{malice}} pour éviter les gardes qui surveillaient le chemin. Son plan, imaginé longtemps à l'avance, fonctionna parfaitement.",
  },
  {
    id: 'dictee-5e-10',
    title: 'Dictée n°10',
    shareCode: '5EME10',
    level: '5e',
    orthoPoint: "L'accord du participe passé avec être et sans auxiliaire",
    lexicalTheme: 'le souvenir',
    starWord: 'nostalgie',
    words: [
      w('la nostalgie', "Tristesse douce liée au regret du passé", ['la nostalgi', 'la nostralgie', 'la nostaljie'], 0),
      w('évoquer', "Rappeler à la mémoire", ['évauquer', 'évocquer', 'aivoquer'], 1),
      w('se remémorer', "Se rappeler avec précision", ['se remaimorer', 'se rémémorer', 'se remmémorer'], 2),
      w('se rappeler', "Faire revenir un souvenir dans sa mémoire", ['se rapeler', 'se rapeller', 'se rappeller'], 3),
      w('se souvenir', "Garder en mémoire", ['se souvenire', 'se souvennir', 'se çouvenir'], 4),
      w('la mémoire', "Capacité de se souvenir", ['la maimoire', 'la mémoir', 'la mémmoire'], 5),
      w('mémorable', "Digne d'être retenu, inoubliable", ['mémorrable', 'maimorable', 'mémorabl'], 6),
      w('inoubliable', "Que l'on ne peut pas oublier", ['inoubliabl', 'innoubliable', 'inoublyable'], 7),
      w('oublieux', "Qui oublie facilement", ['oublieu', 'oubllieux', 'oubliyeux'], 8),
      w('autrefois', "Dans le passé, il y a longtemps", ['autrefoi', 'otrefois', 'autrefoie'], 9),
    ],
    dictationText:
      "Quand elle entre dans le vieux théâtre, Clara est saisie par une étrange émotion. Elle se remémore aussitôt les spectacles vus autrefois avec sa mère quand elle était enfant. Les rideaux rouges sont encore suspendus et d'anciennes affiches sont accrochées aux murs. Clara se souvient de moments mémorables passés dans cet endroit. Les chansons que sa mère aimait lui reviennent aussi en mémoire. Ces souvenirs, conservés à travers les années, lui semblent inoubliables. Elle sent monter en elle une douce nostalgie. Elle n'est pourtant pas oublieuse de ses autres souvenirs, mais celui-ci reste pour elle le plus précieux.",
    fillBlanksText:
      "Quand elle entre dans le vieux théâtre, Clara est saisie par une étrange émotion. Elle {{se remémore}} aussitôt les spectacles vus {{autrefois}} avec sa mère quand elle était enfant. Les rideaux rouges sont encore suspendus et d'anciennes affiches sont accrochées aux murs. Clara {{se souvient}} de moments {{mémorables}} passés dans cet endroit. Les chansons que sa mère aimait lui reviennent aussi en {{mémoire}}. Ces souvenirs, conservés à travers les années, lui semblent {{inoubliables}}. Elle sent monter en elle une douce {{nostalgie}}. Elle n'est pourtant pas {{oublieuse}} de ses autres souvenirs, mais celui-ci reste pour elle le plus précieux.",
  },
  {
    id: 'dictee-5e-11',
    title: 'Dictée n°11',
    shareCode: '5EME11',
    level: '5e',
    orthoPoint: "c'est / s'est",
    lexicalTheme: 'la bonté',
    starWord: 'bienveillance',
    words: [
      w('la bienveillance', "Disposition à vouloir du bien aux autres", ['la bienveillence', 'la bienvaillance', 'la bienveyance'], 0),
      w('encourager', "Donner du courage, soutenir", ['encourajer', 'ancourager', 'encourrager'], 1),
      w('réconforter', "Redonner des forces et du moral", ['raiconforter', 'réconphorter', 'récomforter'], 2),
      w('rassurer', "Rendre la confiance, faire disparaître la peur", ['rasurer', 'raçurer', 'rassurrer'], 3),
      w("l'altruisme", "Souci de faire du bien aux autres sans rien attendre", ["l'altruime", "l'altruïsme", "l'altrouisme"], 4),
      w('la magnanimité', "Grandeur d'âme, générosité qui pardonne", ['la magnanimitée', 'la magnaninité', 'la magnianimité'], 5),
      w('indulgent', "Qui pardonne facilement", ['indulgant', 'indhulgent', 'indulgeant'], 6),
      w('clément', "Qui punit avec douceur, qui pardonne", ['claiment', 'cléman', 'clémant'], 7),
      w('charitable', "Qui aide généreusement les plus démunis", ['charitabl', 'charittable', 'charitablle'], 8),
      w('généreusement', "Avec générosité, sans compter", ['génereusement', 'généreusemant', 'généreuzement'], 9),
    ],
    dictationText:
      "Lorsque le jeune garçon est entré dans le village, c'est une vieille femme qui l'a accueilli et réconforté avec bienveillance. Dans le village, tous la connaissaient pour son altruisme et sa magnanimité : elle parlait généreusement aux plus pauvres, les encourageait, elle aidait les autres sans attendre de récompense, accordait son pardon, se montrait indulgente, charitable et clémente. C'est pourquoi sa bonté était célèbre dans toute la région. Ainsi, dès son arrivée, le jeune garçon s'est senti rassuré. Les douces paroles de la femme l'ont sécurisé et il a pu rejoindre sa famille l'esprit calme. Était-elle une fée ? C'est la question qu'il se posait.",
    fillBlanksText:
      "Lorsque le jeune garçon est entré dans le village, c'est une vieille femme qui l'a accueilli et {{réconforté}} avec {{bienveillance}}. Dans le village, tous la connaissaient pour son {{altruisme}} et sa {{magnanimité}} : elle parlait {{généreusement}} aux plus pauvres, les {{encourageait}}, elle aidait les autres sans attendre de récompense, accordait son pardon, se montrait {{indulgente}}, {{charitable}} et {{clémente}}. C'est pourquoi sa bonté était célèbre dans toute la région. Ainsi, dès son arrivée, le jeune garçon s'est senti {{rassuré}}. Les douces paroles de la femme l'ont sécurisé et il a pu rejoindre sa famille l'esprit calme. Était-elle une fée ? C'est la question qu'il se posait.",
  },
  {
    id: 'dictee-5e-12',
    title: 'Dictée n°12',
    shareCode: '5EME12',
    level: '5e',
    orthoPoint: 'ou / où + dont',
    lexicalTheme: 'le bruit',
    starWord: 'tumulte',
    words: [
      w('le tumulte', "Grand désordre bruyant", ['le tumult', 'le tumullte', 'le thumulte'], 0),
      w('résonner', "Produire un son qui se prolonge", ['résoner', 'raisonner', 'résonné'], 1),
      w('éclater', "Se produire brusquement avec bruit", ['éclatter', 'écclater', 'aiclater'], 2),
      w('gronder', "Produire un bruit sourd et menaçant", ['gromder', 'gronnder', 'grondder'], 3),
      w('retentir', "Se faire entendre avec force", ['retantir', 'rettentir', 'retentire'], 4),
      w('le vacarme', "Bruit très fort et désordonné", ['le vaccarme', 'le vacarm', 'le vakarme'], 5),
      w('le fracas', "Bruit violent d'une chose qui se brise", ['le fraca', 'le fracat', 'le frackas'], 6),
      w('le tapage', "Bruit désordonné et gênant", ['le tappage', 'le tapaje', 'le tapagge'], 7),
      w('assourdissant', "Si fort qu'il rend presque sourd", ['assourdisant', 'asourdissant', 'assourdissent'], 8),
      w('bruyamment', "En faisant beaucoup de bruit", ['bruyament', 'bruillamment', 'bruyemment'], 9),
    ],
    dictationText:
      "La nuit était calme lorsque le premier bruit retentit. Un fracas éclata derrière les maisons, puis un vacarme assourdissant résonna dans la rue où la pénombre régnait. Les habitants s'approchèrent des fenêtres, cherchant derrière les vitres l'origine de ce tumulte. C'était un orage dont les grondements faisaient trembler les maisons. Les habitants ne savaient plus où regarder. Et que faire ? Fallait-il descendre à la cave ou simplement éteindre les lumières ? Au loin, le tonnerre grondait bruyamment. La pluie tomba soudain avec force ou plutôt s'abattit comme un mur d'eau. Lorsque l'orage s'éloigna, les habitants retrouvèrent le calme. Ils racontèrent longtemps cet événement dont ils se souviendraient.",
    fillBlanksText:
      "La nuit était calme lorsque le premier bruit {{retentit}}. Un {{fracas}} {{éclata}} derrière les maisons, puis un {{vacarme}} {{assourdissant}} {{résonna}} dans la rue où la pénombre régnait. Les habitants s'approchèrent des fenêtres, cherchant derrière les vitres l'origine de ce {{tumulte}}. C'était un orage dont les grondements faisaient trembler les maisons. Les habitants ne savaient plus où regarder. Et que faire ? Fallait-il descendre à la cave ou simplement éteindre les lumières ? Au loin, le tonnerre {{grondait}} {{bruyamment}}. La pluie tomba soudain avec force ou plutôt s'abattit comme un mur d'eau. Lorsque l'orage s'éloigna, les habitants retrouvèrent le calme. Ils racontèrent longtemps cet événement dont ils se souviendraient.",
  },
  {
    id: 'dictee-5e-13',
    title: 'Dictée n°13',
    shareCode: '5EME13',
    level: '5e',
    orthoPoint: 'leur / leurs',
    lexicalTheme: 'la colère',
    starWord: 'furieusement',
    words: [
      w('furieusement', "Avec une très grande colère", ['furieusemant', 'furrieusement', 'furieuzement'], 0),
      w("s'emporter", "Se mettre brusquement en colère", ["s'anporter", "s'amporter", "s'emportter"], 1),
      w("s'irriter", "Se mettre en colère peu à peu", ["s'iriter", "s'iritter", "s'irritter"], 2),
      w('enrager', "Éprouver une violente colère", ['enrajer', 'anrager', 'enrrager'], 3),
      w('fulminer', "Exploser de colère en paroles", ['fullminer', 'fulmminer', 'phulminer'], 4),
      w("l'animosité", "Hostilité, mauvais sentiment envers quelqu'un", ["l'animositée", "l'annimosité", "l'animozité"], 5),
      w('le courroux', "Colère violente (mot littéraire)", ['le couroux', 'le courou', 'le courrou'], 6),
      w('la hargne', "Mauvaise humeur agressive", ['la harngne', 'la argne', 'la hargn'], 7),
      w('irascible', "Qui se met facilement en colère", ['irrascible', 'irasible', 'irassible'], 8),
      w('exaspéré', "Poussé à bout, très agacé", ['exazpéré', 'éxaspéré', 'exasperé'], 9),
    ],
    dictationText:
      "Le chef du village s'emporta lorsqu'il apprit la nouvelle. Honteux, certains villageois baissèrent leurs regards devant lui. Il s'irrita contre ceux qui avaient désobéi et fulmina contre leur imprudence. Sa colère grandissait à mesure qu'il entendait leurs excuses. Un homme, exaspéré par ces reproches, finit lui aussi par enrager. La hargne gagnait peu à peu les habitants. Pourtant, une femme resta calme et tenta de modérer les esprits. Elle leur dit de contenir leur colère. Cependant, le chef, encore irascible, parlait furieusement. Ce n'est qu'après un long moment qu'il accepta finalement d'écouter. Son courroux diminua progressivement et le village retrouva son calme. Tous comprirent alors que leur animosité ne résoudrait rien.",
    fillBlanksText:
      "Le chef du village {{s'emporta}} lorsqu'il apprit la nouvelle. Honteux, certains villageois baissèrent leurs regards devant lui. Il {{s'irrita}} contre ceux qui avaient désobéi et {{fulmina}} contre leur imprudence. Sa colère grandissait à mesure qu'il entendait leurs excuses. Un homme, {{exaspéré}} par ces reproches, finit lui aussi par {{enrager}}. La {{hargne}} gagnait peu à peu les habitants. Pourtant, une femme resta calme et tenta de modérer les esprits. Elle leur dit de contenir leur colère. Cependant, le chef, encore {{irascible}}, parlait {{furieusement}}. Ce n'est qu'après un long moment qu'il accepta finalement d'écouter. Son {{courroux}} diminua progressivement et le village retrouva son calme. Tous comprirent alors que leur {{animosité}} ne résoudrait rien.",
  },
  {
    id: 'dictee-5e-14',
    title: 'Dictée n°14',
    shareCode: '5EME14',
    level: '5e',
    orthoPoint: 'quel(s) / quelle(s) + tout / tous / toute(s)',
    lexicalTheme: 'le savoir',
    starWord: 'érudition',
    words: [
      w("l'érudition", "Savoir très étendu acquis par l'étude", ["l'éruditions", "l'érudission", "l'airudition"], 0),
      w('assimiler', "Comprendre et retenir des connaissances", ['assymiler', 'asimiler', 'assimiller'], 1),
      w('enseigner', "Transmettre des connaissances", ['enségner', 'anseigner', 'einseigner'], 2),
      w('un professeur', "Personne qui enseigne", ['un proffesseur', 'un profésseur', 'un professeure'], 3),
      w('une connaissance', "Ce que l'on sait", ['une conaissance', 'une connaisance', 'une connèssance'], 4),
      w('une leçon', "Ce qu'un élève doit apprendre", ['une lesson', 'une leson', 'une lessont'], 5),
      w('averti', "Qui est informé et expérimenté", ['avairti', 'aiverti', 'avverti'], 6),
      w('éclairé', "Qui a des connaissances et du jugement", ['aiclairé', 'éclèré', 'écclairé'], 7),
      w('studieux', "Qui aime étudier", ['studieu', 'sturieux', 'stuadieux'], 8),
      w('savamment', "Avec beaucoup de savoir, habilement", ['savament', 'savemment', 'savammant'], 9),
    ],
    dictationText:
      "Le jeune garçon voulait comprendre le monde qui l'entourait. À l'école, il cherchait à assimiler les nouvelles connaissances et écoutait attentivement son professeur. Celui-ci enseignait l'histoire avec passion et répondait à toutes les questions. Quel bonheur pour ce jeune élève ! Quelles leçons profitables ! Avec le temps, l'élève devenait plus averti et plus studieux. Il lisait tous les ouvrages d'un savant dont les travaux étaient célèbres. Peu à peu, il apprit à distinguer les faits des opinions. Ses connaissances s'enrichissaient et tous les adultes admiraient son esprit de plus en plus éclairé. Il travaillait savamment les notions et prenait plaisir. Pour lui, l'érudition devenait un moyen de mieux comprendre le monde et de grandir.",
    fillBlanksText:
      "Le jeune garçon voulait comprendre le monde qui l'entourait. À l'école, il cherchait à {{assimiler}} les nouvelles {{connaissances}} et écoutait attentivement son {{professeur}}. Celui-ci {{enseignait}} l'histoire avec passion et répondait à toutes les questions. Quel bonheur pour ce jeune élève ! Quelles {{leçons}} profitables ! Avec le temps, l'élève devenait plus {{averti}} et plus {{studieux}}. Il lisait tous les ouvrages d'un savant dont les travaux étaient célèbres. Peu à peu, il apprit à distinguer les faits des opinions. Ses connaissances s'enrichissaient et tous les adultes admiraient son esprit de plus en plus {{éclairé}}. Il travaillait {{savamment}} les notions et prenait plaisir. Pour lui, l'{{érudition}} devenait un moyen de mieux comprendre le monde et de grandir.",
  },
  {
    id: 'dictee-5e-15',
    title: 'Dictée n°15',
    shareCode: '5EME15',
    level: '5e',
    orthoPoint: "même, quelque, sans / s'en",
    lexicalTheme: 'la réflexion et le jugement',
    starWord: 'lucidité',
    words: [
      w('la lucidité', "Capacité de voir et de juger clairement les choses", ['la lusidité', 'la lussidité', 'la luciditée'], 0),
      w("s'assurer", "Vérifier pour être certain", ["s'asurer", "s'açurer", "s'assurrer"], 1),
      w('un examen', "Observation attentive", ['un éxamen', 'un examin', 'un exament'], 2),
      w('un raisonnement', "Enchaînement d'idées qui mène à une conclusion", ['un raisonement', 'un résonnement', 'un raisonnemant'], 3),
      w('un choix', "Décision entre plusieurs possibilités", ['un choi', 'un choit', 'un chois'], 4),
      w('réfléchi', "Qui pense avant d'agir", ['réflèchi', 'réffléchi', 'refléchi'], 5),
      w('avisé', "Qui agit avec intelligence et prudence", ['havisé', 'avizé', 'avissé'], 6),
      w('judicieux', "Qui montre un bon jugement", ['judicieu', 'judissieux', 'judicieus'], 7),
      w('clairvoyant', "Qui voit et comprend les choses avec justesse", ['clervoyant', 'clairvoillant', 'clairevoyant'], 8),
      w('convaincu', "Certain de quelque chose", ['convincu', 'convainqu', 'comvaincu'], 9),
    ],
    dictationText:
      "Après quelques jours d'un long voyage, les compagnons s'arrêtèrent pour réfléchir à leur prochaine étape. Il fallait trouver la meilleure direction afin de poursuivre sans risque. Tous voulaient s'en assurer. Cependant, ils doutaient. La forêt devant eux semblait pouvoir cacher de nombreux secrets. Même le chef, un homme très réfléchi, avisé et clairvoyant, hésitait encore. Leur examen attentif de la carte permit de comparer quelques chemins difficiles. Le chef proposa une solution judicieuse et tous en discutèrent calmement. Ils savaient qu'il leur fallait agir avec une totale lucidité. Le chef expliqua son raisonnement logique. Chacun comprit pourquoi ce choix était le plus raisonnable. Ils étaient même convaincus d'avoir pris la bonne décision. Ils avancèrent donc sans hésiter.",
    fillBlanksText:
      "Après quelques jours d'un long voyage, les compagnons s'arrêtèrent pour réfléchir à leur prochaine étape. Il fallait trouver la meilleure direction afin de poursuivre sans risque. Tous voulaient s'en assurer. Cependant, ils doutaient. La forêt devant eux semblait pouvoir cacher de nombreux secrets. Même le chef, un homme très {{réfléchi}}, {{avisé}} et {{clairvoyant}}, hésitait encore. Leur {{examen}} attentif de la carte permit de comparer quelques chemins difficiles. Le chef proposa une solution {{judicieuse}} et tous en discutèrent calmement. Ils savaient qu'il leur fallait agir avec une totale {{lucidité}}. Le chef expliqua son {{raisonnement}} logique. Chacun comprit pourquoi ce {{choix}} était le plus raisonnable. Ils étaient même {{convaincus}} d'avoir pris la bonne décision. Ils avancèrent donc sans hésiter.",
  },
  {
    id: 'dictee-5e-16',
    title: 'Dictée n°16',
    shareCode: '5EME16',
    level: '5e',
    orthoPoint: 'Le futur',
    lexicalTheme: "l'apaisement",
    starWord: 'quiétude',
    words: [
      w('la quiétude', "Calme paisible, tranquillité", ['la quiètude', 'la quiétute', 'la kiétude'], 0),
      w('apaiser', "Rendre calme", ['appaiser', 'apayser', 'apéser'], 1),
      w('adoucir', "Rendre plus doux", ['adousir', 'addoucir', 'adouçire'], 2),
      w('modérer', "Diminuer la force, l'excès", ['maudérer', 'moddérer', 'modérrer'], 3),
      w('pacifier', "Ramener la paix", ['passifier', 'pacyfier', 'paçifier'], 4),
      w('soulager', "Diminuer une douleur ou une peine", ['çoulager', 'soullager', 'soulajer'], 5),
      w('une consolation', "Réconfort donné à quelqu'un qui a du chagrin", ['une consolassion', 'une consollation', 'une consolasion'], 6),
      w('la tranquillité', "État calme et paisible", ['la tranquilité', 'la tranquillitée', 'la tranquilitté'], 7),
      w('paisible', "Calme et doux", ['pésible', 'paisibl', 'paissible'], 8),
      w('serein', "Calme et confiant", ['serin', 'sereint', 'cerein'], 9),
    ],
    dictationText:
      "Après la dispute, la maison retrouvera lentement son calme. La mère cherchera d'abord à pacifier les échanges et demandera à chacun de parler moins fort. Son ton doux apaisera les esprits et adoucira les paroles. Elle proposera de modérer les reproches. Peu à peu, une profonde tranquillité s'installera dans la pièce. Les voix deviendront plus basses et les visages plus détendus. Le calme retrouvé apportera une véritable consolation aux enfants, rendus inquiets par les cris des adultes. Tous parleront à nouveau avec douceur. Bientôt, l'atmosphère deviendra paisible et sereine. Chacun gagnera en confiance et se sentira mieux. Les sourires reviendront sur les visages. Dans cette maison enfin silencieuse, tous goûteront à la quiétude retrouvée et oublieront leur colère.",
    fillBlanksText:
      "Après la dispute, la maison retrouvera lentement son calme. La mère cherchera d'abord à {{pacifier}} les échanges et demandera à chacun de parler moins fort. Son ton doux {{apaisera}} les esprits et {{adoucira}} les paroles. Elle proposera de {{modérer}} les reproches. Peu à peu, une profonde {{tranquillité}} s'installera dans la pièce. Les voix deviendront plus basses et les visages plus détendus. Le calme retrouvé apportera une véritable {{consolation}} aux enfants, rendus inquiets par les cris des adultes. Tous parleront à nouveau avec douceur. Bientôt, l'atmosphère deviendra {{paisible}} et {{sereine}}. Chacun gagnera en confiance et se sentira mieux. Les sourires reviendront sur les visages. Dans cette maison enfin silencieuse, tous goûteront à la {{quiétude}} retrouvée et oublieront leur colère.",
  },
];
