// Lexique du corpus 5e : mots de la même famille + synonymes, pour les
// 160 mots des 16 dictées (demande de la collègue, mail du 06/09/2026,
// point 5 : exercice « mots de la même famille et synonymes »).
//
// ORIGINE : contenu rédigé par l'IA le 19/09/2026 à partir des définitions
// de la collègue (scripts/dictees-5e-data.mjs) — ce n'est PAS un document
// de la collègue. Chaque entrée est chargée en base avec lexicon_validated =
// false ; la collègue relit, corrige et valide dictée par dictée dans le
// panneau 🎯 Parcours → Personnaliser les mots → onglet 🧩 Famille & synonymes.
//
// Conventions :
//  - famille   : dérivés et composés partageant le radical (jamais une simple
//                flexion du mot : féminin, pluriel, forme conjuguée).
//                Liste courte si la famille est pauvre — jamais de remplissage.
//  - synonymes : même classe grammaticale que le mot, dans le SENS de la
//                définition retenue par la collègue, niveau collège.
//  - tout est écrit sans article, en minuscules ; les verbes pronominaux
//                gardent leur pronom (« se cacher »).
//
// Consommé par scripts/apply-lexique-5e.mjs.

const e = (position, word, famille, synonymes) => ({ position, word, famille, synonymes });

export const LEXIQUE_5E = {
  "dictee-5e-1": [
    e(0, "scruter",
      ["scrutateur", "scrutin"],
      ["examiner", "inspecter", "observer", "fouiller du regard"]),
    e(1, "examiner",
      ["examen", "examinateur", "réexaminer"],
      ["inspecter", "étudier", "observer", "analyser"]),
    e(2, "apercevoir",
      ["aperçu", "percevoir", "perception", "perceptible", "imperceptible"],
      ["entrevoir", "voir", "remarquer"]),
    e(3, "observer",
      ["observation", "observateur", "observatoire", "observable"],
      ["regarder", "examiner", "surveiller", "scruter"]),
    e(4, "un détail",
      ["détailler", "détaillé", "détaillant"],
      ["élément", "précision", "particularité"]),
    e(5, "un indice",
      ["indiquer", "indication", "indicateur", "index"],
      ["signe", "trace", "piste", "marque"]),
    e(6, "le regard",
      ["regarder"],
      ["coup d'œil", "œil", "vue"]),
    e(7, "curieux",
      ["curiosité", "curieusement"],
      ["intéressé", "intrigué", "avide de savoir"]),
    e(8, "visible",
      ["visibilité", "invisible", "visiblement", "vision", "visuel"],
      ["apparent", "perceptible", "observable", "distinct"]),
    e(9, "attentivement",
      ["attention", "attentif", "inattentif", "inattention"],
      ["soigneusement", "avec soin", "minutieusement", "scrupuleusement"]),
  ],

  "dictee-5e-2": [
    e(0, "arpenter",
      ["arpent", "arpentage", "arpenteur"],
      ["parcourir", "sillonner", "traverser"]),
    e(1, "contourner",
      ["contour", "tour", "tourner", "détourner", "entourer"],
      ["éviter", "tourner autour de", "faire le tour de"]),
    e(2, "s'aventurer",
      ["aventure", "aventurier", "aventureux", "mésaventure"],
      ["se risquer", "se hasarder", "s'engager"]),
    e(3, "un sentier",
      [],
      ["chemin", "piste", "allée", "voie"]),
    e(4, "un périple",
      [],
      ["voyage", "expédition", "odyssée", "circuit"]),
    e(5, "un détour",
      ["détourner", "détournement", "tour", "contour", "contourner"],
      ["crochet", "déviation", "boucle"]),
    e(6, "un paysage",
      ["pays", "paysan", "paysagiste", "dépaysement", "dépayser"],
      ["panorama", "vue", "site", "décor"]),
    e(7, "un itinéraire",
      ["itinérant", "itinérance"],
      ["parcours", "trajet", "chemin", "route"]),
    e(8, "isolé",
      ["isoler", "isolement", "isolation", "isolant", "isoloir"],
      ["écarté", "retiré", "éloigné", "solitaire"]),
    e(9, "inexploré",
      ["explorer", "exploration", "explorateur"],
      ["inconnu", "vierge", "méconnu", "ignoré"]),
  ],

  "dictee-5e-3": [
    e(0, "présager",
      ["présage"],
      ["annoncer", "prédire", "laisser prévoir"]),
    e(1, "se méfier",
      ["méfiance", "méfiant", "confiance", "se fier", "défiance"],
      ["se défier", "se garder de", "douter de", "soupçonner"]),
    e(2, "se dissimuler",
      ["dissimulation", "dissimulateur", "dissimulé", "simuler"],
      ["se cacher", "se dérober", "se tapir", "s'éclipser"]),
    e(3, "guetter",
      ["guet", "guetteur", "aguets", "guet-apens"],
      ["épier", "surveiller", "attendre", "observer"]),
    e(4, "une menace",
      ["menacer", "menaçant"],
      ["danger", "péril", "risque"]),
    e(5, "la vigilance",
      ["vigilant", "vigile", "veiller", "veille", "veilleur"],
      ["attention", "surveillance", "prudence"]),
    e(6, "l'inquiétude",
      ["inquiet", "inquiéter", "inquiétant", "quiétude"],
      ["anxiété", "souci", "crainte", "appréhension"]),
    e(7, "une alerte",
      ["alerter"],
      ["alarme", "avertissement", "signal"]),
    e(8, "inhabituel",
      ["habitude", "habituel", "habituer", "habituellement", "inhabituellement"],
      ["inaccoutumé", "insolite", "rare", "anormal"]),
    e(9, "prudemment",
      ["prudence", "prudent", "imprudent", "imprudence", "imprudemment"],
      ["précautionneusement", "avec précaution", "avec prudence", "sagement"]),
  ],

  "dictee-5e-4": [
    e(0, "irradier",
      ["irradiation", "radiation", "radieux", "rayon", "rayonner"],
      ["rayonner", "briller", "resplendir", "se diffuser"]),
    e(1, "scintiller",
      ["scintillement", "scintillant", "scintillation"],
      ["briller", "étinceler", "pétiller", "chatoyer"]),
    e(2, "refléter",
      ["reflet", "réfléchir", "réflexion", "réflecteur"],
      ["renvoyer", "réverbérer", "réfléchir"]),
    e(3, "illuminer",
      ["illumination", "lumière", "lumineux", "luminosité", "luminaire"],
      ["éclairer", "embraser", "inonder de lumière"]),
    e(4, "faiblir",
      ["faible", "faiblesse", "affaiblir", "affaiblissement", "faiblement"],
      ["diminuer", "baisser", "décliner", "s'affaiblir"]),
    e(5, "la pénombre",
      ["ombre", "ombrage", "ombragé", "ombrelle", "ombreux"],
      ["demi-jour", "clair-obscur", "demi-obscurité"]),
    e(6, "une lueur",
      ["luire", "reluire", "luisant", "reluisant"],
      ["clarté", "lumière", "halo", "reflet"]),
    e(7, "un rayon",
      ["rayonner", "rayonnement", "rayonnant", "irradier"],
      ["faisceau", "trait de lumière", "jet de lumière"]),
    e(8, "un éclat",
      ["éclater", "éclatant", "éclatement"],
      ["brillance", "lumière", "scintillement", "splendeur"]),
    e(9, "éblouissant",
      ["éblouir", "éblouissement"],
      ["aveuglant", "étincelant", "resplendissant", "éclatant"]),
  ],

  "dictee-5e-5": [
    e(0, "un enchantement",
      ["enchanter", "enchanteur", "chant"],
      ["émerveillement", "ravissement", "charme", "magie"]),
    e(1, "admirer",
      ["admiration", "admirateur", "admirable", "admiratif"],
      ["contempler", "s'émerveiller devant", "apprécier"]),
    e(2, "contempler",
      ["contemplation", "contemplatif", "contemplateur"],
      ["admirer", "regarder", "observer", "fixer"]),
    e(3, "s'émerveiller",
      ["merveille", "merveilleux", "émerveillement", "merveilleusement"],
      ["s'extasier", "s'enthousiasmer", "admirer"]),
    e(4, "s'extasier",
      ["extase", "extatique"],
      ["s'émerveiller", "s'enthousiasmer", "admirer"]),
    e(5, "une merveille",
      ["merveilleux", "merveilleusement", "s'émerveiller", "émerveillement"],
      ["prodige", "splendeur", "chef-d'œuvre", "miracle"]),
    e(6, "un éblouissement",
      ["éblouir", "éblouissant"],
      ["émerveillement", "fascination", "enchantement", "ravissement"]),
    e(7, "fascinant",
      ["fasciner", "fascination"],
      ["captivant", "envoûtant", "passionnant", "attirant"]),
    e(8, "envoûtant",
      ["envoûter", "envoûtement", "envoûteur"],
      ["ensorcelant", "fascinant", "charmeur", "captivant"]),
    e(9, "profondément",
      ["profond", "profondeur", "approfondir", "approfondissement"],
      ["intensément", "fortement", "vivement", "extrêmement"]),
  ],

  "dictee-5e-6": [
    e(0, "la persévérance",
      ["persévérer", "persévérant"],
      ["ténacité", "obstination", "constance", "opiniâtreté"]),
    e(1, "entreprendre",
      ["entreprise", "entrepreneur", "entreprenant", "prendre", "apprendre"],
      ["commencer", "engager", "se lancer dans", "démarrer"]),
    e(2, "s'efforcer",
      ["effort", "force", "forcer", "renforcer", "forcément"],
      ["tenter de", "s'appliquer à", "tâcher de", "s'évertuer à"]),
    e(3, "le courage",
      ["courageux", "courageusement", "encourager", "décourager", "encouragement"],
      ["bravoure", "vaillance", "audace", "hardiesse"]),
    e(4, "un effort",
      ["s'efforcer", "force", "forcer", "renforcer"],
      ["peine", "travail", "application", "énergie"]),
    e(5, "déterminé",
      ["déterminer", "détermination", "indéterminé", "terme"],
      ["décidé", "résolu", "ferme", "volontaire"]),
    e(6, "opiniâtre",
      ["opiniâtreté", "opinion"],
      ["obstiné", "tenace", "entêté", "acharné"]),
    e(7, "tenace",
      ["ténacité", "tenir", "tenue"],
      ["persévérant", "obstiné", "opiniâtre", "acharné"]),
    e(8, "résolument",
      ["résolu", "résolution", "résoudre", "irrésolu"],
      ["fermement", "avec décision", "sans hésiter", "hardiment"]),
    e(9, "inlassablement",
      ["lasser", "las", "lassitude", "inlassable", "délasser"],
      ["sans relâche", "infatigablement", "sans cesse", "sans se lasser"]),
  ],

  "dictee-5e-7": [
    e(0, "serpenter",
      ["serpent", "serpentin"],
      ["zigzaguer", "onduler", "faire des lacets"]),
    e(1, "s'élever",
      ["élévation", "élevé", "élève", "élevage", "surélever"],
      ["monter", "se dresser", "grimper", "s'ériger"]),
    e(2, "surplomber",
      ["surplomb", "plomb", "aplomb", "plomber"],
      ["dominer", "avancer au-dessus de", "se dresser au-dessus de"]),
    e(3, "culminer",
      ["culminant"],
      ["atteindre son sommet", "dominer"]),
    e(4, "un sommet",
      [],
      ["cime", "pic", "faîte", "crête"]),
    e(5, "un versant",
      ["verser", "renverser", "déverser", "versement"],
      ["pente", "flanc", "côté"]),
    e(6, "une falaise",
      [],
      ["paroi", "escarpement", "à-pic", "rocher"]),
    e(7, "escarpé",
      ["escarpement"],
      ["abrupt", "raide", "à pic"]),
    e(8, "abrupt",
      ["abruptement"],
      ["escarpé", "raide", "à pic", "vertical"]),
    e(9, "majestueusement",
      ["majesté", "majestueux"],
      ["noblement", "solennellement", "grandiosement", "superbement"]),
  ],

  "dictee-5e-8": [
    e(0, "énigmatique",
      ["énigme"],
      ["mystérieux", "obscur", "incompréhensible", "impénétrable"]),
    e(1, "disparaître",
      ["disparition", "disparu", "paraître", "apparaître", "apparition"],
      ["s'évanouir", "s'effacer", "s'éclipser", "se volatiliser"]),
    e(2, "surgir",
      ["surgissement", "ressurgir"],
      ["apparaître", "jaillir", "se dresser", "émerger"]),
    e(3, "déceler",
      ["décelable", "indécelable"],
      ["découvrir", "détecter", "repérer", "remarquer"]),
    e(4, "dévoiler",
      ["voile", "voiler", "dévoilement", "voilé"],
      ["révéler", "divulguer", "montrer", "découvrir"]),
    e(5, "une silhouette",
      [],
      ["ombre", "forme", "contour", "profil"]),
    e(6, "une apparition",
      ["apparaître", "apparent", "apparemment", "paraître", "disparition"],
      ["surgissement", "manifestation", "venue", "arrivée"]),
    e(7, "étrange",
      ["étranger", "étrangement", "étrangeté"],
      ["bizarre", "insolite", "curieux", "singulier"]),
    e(8, "insaisissable",
      ["saisir", "saisissable", "saisie", "saisissant"],
      ["fuyant", "impalpable", "incompréhensible", "indéfinissable"]),
    e(9, "mystérieusement",
      ["mystère", "mystérieux"],
      ["étrangement", "bizarrement", "secrètement", "curieusement"]),
  ],

  "dictee-5e-9": [
    e(0, "la perfidie",
      ["perfide", "perfidement"],
      ["traîtrise", "trahison", "déloyauté", "fourberie"]),
    e(1, "leurrer",
      ["leurre"],
      ["tromper", "duper", "berner", "abuser"]),
    e(2, "feindre",
      ["feinte"],
      ["simuler", "faire semblant de", "jouer la comédie"]),
    e(3, "manigancer",
      ["manigance"],
      ["comploter", "tramer", "combiner", "machiner"]),
    e(4, "dissimuler",
      ["dissimulation", "dissimulateur", "dissimulé", "simuler"],
      ["cacher", "masquer", "camoufler", "taire"]),
    e(5, "un stratagème",
      ["stratégie", "stratège", "stratégique"],
      ["ruse", "subterfuge", "astuce", "manœuvre"]),
    e(6, "la malice",
      ["malicieux", "malicieusement", "mal", "malin"],
      ["espièglerie", "taquinerie", "moquerie", "ruse"]),
    e(7, "fourbe",
      ["fourberie"],
      ["hypocrite", "sournois", "perfide", "trompeur"]),
    e(8, "sournois",
      ["sournoisement", "sournoiserie"],
      ["dissimulé", "hypocrite", "fourbe", "perfide"]),
    e(9, "astucieusement",
      ["astuce", "astucieux"],
      ["habilement", "ingénieusement", "adroitement", "finement"]),
  ],

  "dictee-5e-10": [
    e(0, "la nostalgie",
      ["nostalgique"],
      ["regret", "mélancolie", "mal du pays", "tristesse"]),
    e(1, "évoquer",
      ["évocation", "évocateur"],
      ["rappeler", "mentionner", "faire penser à", "citer"]),
    e(2, "se remémorer",
      ["mémoire", "mémorable", "mémoriser", "commémorer", "immémorial"],
      ["se rappeler", "se souvenir de", "revoir"]),
    e(3, "se rappeler",
      ["rappel", "appeler", "appel", "appellation"],
      ["se souvenir de", "se remémorer", "revoir"]),
    e(4, "se souvenir",
      ["souvenir", "venir"],
      ["se rappeler", "se remémorer", "garder en mémoire"]),
    e(5, "la mémoire",
      ["mémoriser", "mémorable", "mémorisation", "commémorer", "remémorer"],
      ["souvenir"]),
    e(6, "mémorable",
      ["mémoire", "mémoriser", "commémorer", "immémorial"],
      ["inoubliable", "marquant", "historique", "remarquable"]),
    e(7, "inoubliable",
      ["oublier", "oubli", "oublieux", "oubliette"],
      ["mémorable", "marquant", "impérissable", "ineffaçable"]),
    e(8, "oublieux",
      ["oublier", "oubli", "inoubliable", "oubliette"],
      ["distrait", "étourdi", "négligent"]),
    e(9, "autrefois",
      ["autre", "fois", "parfois", "quelquefois"],
      ["jadis", "auparavant", "anciennement", "dans le temps"]),
  ],

  "dictee-5e-11": [
    e(0, "la bienveillance",
      ["bienveillant", "malveillance", "malveillant", "bien"],
      ["bonté", "gentillesse", "indulgence", "générosité"]),
    e(1, "encourager",
      ["courage", "courageux", "encouragement", "décourager", "encourageant"],
      ["soutenir", "stimuler", "réconforter", "pousser"]),
    e(2, "réconforter",
      ["réconfort", "réconfortant", "confort", "confortable", "fort"],
      ["consoler", "soutenir", "remonter le moral", "revigorer"]),
    e(3, "rassurer",
      ["sûr", "sûreté", "assurer", "rassurant", "assurance"],
      ["tranquilliser", "apaiser", "calmer", "sécuriser"]),
    e(4, "l'altruisme",
      ["altruiste"],
      ["générosité", "dévouement", "désintéressement", "bonté"]),
    e(5, "la magnanimité",
      ["magnanime", "magnanimement"],
      ["grandeur d'âme", "générosité", "clémence", "noblesse"]),
    e(6, "indulgent",
      ["indulgence"],
      ["clément", "compréhensif", "tolérant", "bienveillant"]),
    e(7, "clément",
      ["clémence"],
      ["indulgent", "magnanime", "miséricordieux", "doux"]),
    e(8, "charitable",
      ["charité", "charitablement"],
      ["généreux", "bon", "secourable", "humain"]),
    e(9, "généreusement",
      ["générosité", "généreux"],
      ["largement", "abondamment", "sans compter"]),
  ],

  "dictee-5e-12": [
    e(0, "le tumulte",
      ["tumultueux", "tumultueusement"],
      ["agitation", "vacarme", "désordre", "tapage"]),
    e(1, "résonner",
      ["résonance", "résonateur", "son", "sonner", "sonore"],
      ["retentir", "vibrer", "sonner", "tinter"]),
    e(2, "éclater",
      ["éclat", "éclatant", "éclatement"],
      ["exploser", "détoner", "retentir", "se déclencher"]),
    e(3, "gronder",
      ["grondement", "gronderie"],
      ["rugir", "tonner", "mugir", "rouler"]),
    e(4, "retentir",
      ["retentissement", "retentissant"],
      ["résonner", "éclater", "sonner", "tonner"]),
    e(5, "le vacarme",
      [],
      ["tumulte", "tapage", "boucan", "chahut"]),
    e(6, "le fracas",
      ["fracasser", "fracassant"],
      ["vacarme", "grondement", "bruit", "tonnerre"]),
    e(7, "le tapage",
      ["taper", "tape", "tapageur", "tapageusement"],
      ["vacarme", "chahut", "tumulte", "raffut"]),
    e(8, "assourdissant",
      ["sourd", "assourdir", "assourdissement", "surdité", "sourdement"],
      ["étourdissant", "tonitruant", "fracassant", "bruyant"]),
    e(9, "bruyamment",
      ["bruit", "bruyant", "bruire", "bruissement", "ébruiter"],
      ["fort", "à grand bruit", "tapageusement", "avec fracas"]),
  ],

  "dictee-5e-13": [
    e(0, "furieusement",
      ["furie", "furieux", "fureur", "furibond"],
      ["rageusement", "violemment", "avec fureur", "avec colère"]),
    e(1, "s'emporter",
      ["emportement", "emporté", "porter"],
      ["se fâcher", "s'irriter", "exploser", "s'énerver"]),
    e(2, "s'irriter",
      ["irritation", "irritable", "irritant"],
      ["se fâcher", "s'énerver", "s'agacer", "s'emporter"]),
    e(3, "enrager",
      ["rage", "rageur", "rageusement", "enragé", "rager"],
      ["fulminer", "bouillir de colère", "s'emporter", "rager"]),
    e(4, "fulminer",
      ["fulminant"],
      ["tempêter", "tonner", "s'emporter", "exploser"]),
    e(5, "l'animosité",
      [],
      ["hostilité", "antipathie", "rancune", "aversion"]),
    e(6, "le courroux",
      ["courroucer", "courroucé"],
      ["colère", "fureur", "irritation", "rage"]),
    e(7, "la hargne",
      ["hargneux", "hargneusement"],
      ["agressivité", "méchanceté", "animosité", "rage"]),
    e(8, "irascible",
      ["irascibilité"],
      ["coléreux", "colérique", "emporté", "irritable"]),
    e(9, "exaspéré",
      ["exaspérer", "exaspération", "exaspérant"],
      ["excédé", "agacé", "énervé", "à bout"]),
  ],

  "dictee-5e-14": [
    e(0, "l'érudition",
      ["érudit"],
      ["savoir", "culture", "connaissance", "science"]),
    e(1, "assimiler",
      ["assimilation", "assimilable", "similaire", "inassimilable"],
      ["comprendre", "apprendre", "intégrer", "retenir"]),
    e(2, "enseigner",
      ["enseignement", "enseignant", "enseigne", "renseigner"],
      ["instruire", "apprendre", "former", "éduquer"]),
    e(3, "un professeur",
      ["professer", "professorat", "professoral", "profession"],
      ["enseignant", "maître", "pédagogue"]),
    e(4, "une connaissance",
      ["connaître", "connaisseur", "reconnaître", "méconnaissance", "inconnu"],
      ["savoir", "notion", "compétence", "culture"]),
    e(5, "une leçon",
      [],
      ["cours", "enseignement", "apprentissage", "instruction"]),
    e(6, "averti",
      ["avertir", "avertissement", "avertisseur"],
      ["informé", "expérimenté", "au courant", "instruit"]),
    e(7, "éclairé",
      ["éclairer", "clair", "clarté", "éclairage", "éclaircir"],
      ["instruit", "cultivé", "avisé", "savant"]),
    e(8, "studieux",
      ["étude", "étudier", "étudiant", "studieusement"],
      ["appliqué", "travailleur", "sérieux", "assidu"]),
    e(9, "savamment",
      ["savoir", "savant"],
      ["habilement", "avec science", "ingénieusement"]),
  ],

  "dictee-5e-15": [
    e(0, "la lucidité",
      ["lucide", "lucidement"],
      ["clairvoyance", "discernement", "perspicacité", "clarté d'esprit"]),
    e(1, "s'assurer",
      ["sûr", "assurance", "sûreté", "rassurer", "assurément"],
      ["vérifier", "contrôler", "s'informer"]),
    e(2, "un examen",
      ["examiner", "examinateur", "examinatrice", "réexaminer"],
      ["observation", "étude", "analyse", "inspection"]),
    e(3, "un raisonnement",
      ["raison", "raisonner", "raisonnable", "déraisonnable", "irraisonné"],
      ["réflexion", "argumentation", "démonstration", "logique"]),
    e(4, "un choix",
      ["choisir"],
      ["décision", "option", "sélection", "préférence"]),
    e(5, "réfléchi",
      ["réfléchir", "réflexion", "irréfléchi", "réflexe"],
      ["posé", "prudent", "sensé", "raisonnable"]),
    e(6, "avisé",
      ["avis", "aviser", "malavisé", "préavis"],
      ["sage", "prudent", "réfléchi", "judicieux"]),
    e(7, "judicieux",
      ["judicieusement", "juge", "juger", "jugement"],
      ["pertinent", "sensé", "avisé", "raisonnable"]),
    e(8, "clairvoyant",
      ["clairvoyance", "clair", "voyant", "voir"],
      ["lucide", "perspicace", "pénétrant", "sagace"]),
    e(9, "convaincu",
      ["convaincre", "conviction", "convaincant", "vaincre"],
      ["certain", "sûr", "persuadé", "assuré"]),
  ],

  "dictee-5e-16": [
    e(0, "la quiétude",
      ["inquiétude", "inquiet", "inquiéter"],
      ["tranquillité", "calme", "sérénité", "paix"]),
    e(1, "apaiser",
      ["paix", "apaisement", "apaisant", "paisible", "pacifier"],
      ["calmer", "tranquilliser", "adoucir", "rasséréner"]),
    e(2, "adoucir",
      ["doux", "douceur", "adoucissement", "adoucissant", "doucement"],
      ["atténuer", "tempérer", "calmer", "alléger"]),
    e(3, "modérer",
      ["modération", "modéré", "modérateur", "immodéré"],
      ["tempérer", "freiner", "atténuer", "limiter"]),
    e(4, "pacifier",
      ["paix", "pacifique", "pacification", "paisible", "apaiser"],
      ["apaiser", "calmer", "réconcilier", "rétablir la paix"]),
    e(5, "soulager",
      ["soulagement", "léger", "alléger", "légèreté"],
      ["apaiser", "calmer", "alléger", "atténuer"]),
    e(6, "une consolation",
      ["consoler", "consolant", "inconsolable", "consolateur"],
      ["réconfort", "soutien", "apaisement", "soulagement"]),
    e(7, "la tranquillité",
      ["tranquille", "tranquillement", "tranquilliser", "tranquillisant"],
      ["calme", "quiétude", "sérénité", "paix"]),
    e(8, "paisible",
      ["paix", "paisiblement", "apaiser", "pacifique"],
      ["calme", "tranquille", "serein", "doux"]),
    e(9, "serein",
      ["sérénité", "sereinement", "rasséréner"],
      ["calme", "paisible", "tranquille", "confiant"]),
  ],
};

export const LEXIQUE_5E_ENTRIES = Object.entries(LEXIQUE_5E).flatMap(([dicteeId, words]) =>
  words.map((w) => ({ dicteeId, ...w })),
);
